### ISSUE TITLE
CONVERT TO JAVASCRIPT

### ISSUE THREAD

**Issue by qchen59** [qchen59/TeachersPetBot#2]
From TeachersPetBot created by [War-Keeper](https://github.com/War-Keeper): War-Keeper/TeachersPetBot#38  

the discord.py API is deprecated and is no longer maintained by its owner, so the bot will need to be converted to js, the original code that discord is written in.

**Comment by hughman98** [comment]
Our project priorities changed, leaving this issue irrelevant. So I'm closing it.
