### ISSUE TITLE
Use the Database for to update the calender after each related command

### ISSUE THREAD

**Issue by qchen59** [qchen59/TeachersPetBot#5]
From TeachersPetBot created by [War-Keeper](https://github.com/War-Keeper): War-Keeper/TeachersPetBot#34  

The current code doesnt use the db after initializing the bot,

**Comment by Arcane94** [comment]
Looks like this had been fixed. The calendar is updated with database entries when the bot is started. Also, after each event creation command, the database is updated and subsequently, the calendar is updated with database entries.
